version: '3.8'

services:
  superset:
    build: .
    container_name: superset
    environment:
      - SUPERSET_ENV=production
      - SUPERSET_DATABASE_URI=postgresql+psycopg2://superset:superset@db:5432/superset
      - SNOWFLAKE_URI=${SNOWFLAKE_URI}
    ports:
      - "8088:8088"
    command: |
      bash -c "
        pip install snowflake-sqlalchemy pyyaml &&
        echo 'Database before' &&
        superset db upgrade &&
        echo 'Database upgraded' &&
        superset fab create-admin --username admin --firstname Admin --lastname User --email admin@superset.com --password admin &&
        echo 'Admin user created' &&
        superset init &&
        echo 'Superset initialized' &&
        # TODO: This is very hacky and works only for the outliers dashboard, change this.
        SNOWFLAKE_URI=\"$SNOWFLAKE_URI\" envsubst < /app/dashboards/outliers/databases/Snowflake.yaml > /app/dashboards/outliers/databases/Snowflake.yaml.tmp &&
        mv /app/dashboards/outliers/databases/Snowflake.yaml.tmp /app/dashboards/outliers/databases/Snowflake.yaml &&
        /app/scripts/import_dashboards.sh &&
        superset run -p 8088 --with-threads --reload --debugger --host=0.0.0.0
      "
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: